=== AMRC-FactoryPlus/amrc-connectivity-stack/schemas/Electrical_Grid/Electrical_Grid-v1.json
{
  "$id": "urn:uuid:935b7210-c2f6-402c-90d2-ebe3e5ffffd2",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Electrical Grid",
  "type": "object",
  "properties": {
    "Schema_UUID": {
      "const": "935b7210-c2f6-402c-90d2-ebe3e5ffffd2"
    },
    "Instance_UUID": {
      "description": "The unique identifier for this object. (A UUID specified by RFC4122).",
      "type": "string",
      "format": "uuid"
    },
    "Device_Information": {
      "$ref": "urn:uuid:2dd093e9-1450-44c5-be8c-c0d78e48219b"
    },
    "Regions": {
      "type": "object",
      "patternProperties": {
        "^[a-zA-Z0-9_]*$": {
          "$ref": "urn:uuid:a15a0500-88ee-4e56-af43-224a874ccf32"
        }
      }
    }
  },
  "required": [
    "Schema_UUID",
    "Instance_UUID"
  ]
}

=== AMRC-FactoryPlus/amrc-connectivity-stack/temp-model.json
{"Regions":{"undefined":{"Schema_UUID":"a15a0500-88ee-4e56-af43-224a874ccf32","Instance_UUID":"b2713976-1ee6-461d-9705-4e570616bbc5"},"asdfasdfasdfasdf":{"Schema_UUID":"a15a0500-88ee-4e56-af43-224a874ccf32","Instance_UUID":"135bc706-9188-4cd8-8fea-7d48dfcfd5f4","Generation_Mix":{"Fuels":{"Solar":{"Power":{"Value":"100","Method":"GET","Schema_UUID":"b16275f1-e443-4c41-a482-fcbdfbd20769","Documentation":"Generated power of particular fuel","Sparkplug_Type":"FloatLE","Record_To_Historian":true},"Schema_UUID":"a6cc8a36-fa97-4157-a277-27468bd08b8a","Instance_UUID":"2938e209-dba8-4a57-b2f7-55175a587dae"}},"Schema_UUID":"b171ea92-a693-4a62-8448-6df1c7b1ff44","Instance_UUID":"6477996c-aaa6-4148-85a0-37d5bbd20275"}}},"Schema_UUID":"935b7210-c2f6-402c-90d2-ebe3e5ffffd2","Instance_UUID":"d53d64e8-c5e6-43b8-b468-37737ecdffbe","Device_Information":{"Model":{"Method":"GET","Schema_UUID":"b16275f1-e443-4c41-a482-fcbdfbd20769","Documentation":"The model name or number of this device.","Sparkplug_Type":"String","Record_To_Historian":true},"Serial":{"Method":"GET","Schema_UUID":"b16275f1-e443-4c41-a482-fcbdfbd20769","Documentation":"The serial number or unique identifier of the device.","Sparkplug_Type":"String","Record_To_Historian":true},"Status":{"Method":"GET","Schema_UUID":"b16275f1-e443-4c41-a482-fcbdfbd20769","Documentation":"The current status of the device","Sparkplug_Type":"String","Record_To_Historian":true},"Uptime":{"Method":"GET","Schema_UUID":"b16275f1-e443-4c41-a482-fcbdfbd20769","Documentation":"The amount of time that the device has been online","Sparkplug_Type":"String","Record_To_Historian":true},"Battery":{"Time_Remaining":{"Method":"GET","Schema_UUID":"b16275f1-e443-4c41-a482-fcbdfbd20769","Documentation":"The amount of time remaining until the battery is depleted","Sparkplug_Type":"String","Record_To_Historian":true}},"MAC_Address":{"Method":"GET","Schema_UUID":"b16275f1-e443-4c41-a482-fcbdfbd20769","Documentation":"The MAC address of the interface on the device that Factory+ connects to","Sparkplug_Type":"String","Record_To_Historian":true},"Schema_UUID":"2dd093e9-1450-44c5-be8c-c0d78e48219b","Instance_UUID":"4e51d521-f32c-4493-af1d-f84d0b6b320d"}}
